# Generated by Django 4.0.2 on 2022-03-15 20:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_bairro', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_beneficiado', models.CharField(max_length=150)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('contato', models.CharField(blank=True, max_length=11, null=True)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_residencia', models.CharField(blank=True, max_length=15, null=True)),
                ('complemento', models.CharField(blank=True, max_length=200, null=True)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registros.bairro')),
            ],
        ),
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficio', models.CharField(max_length=125)),
                ('tipo_beneficio', models.CharField(default='Beneficio Eventual', max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=125)),
                ('resposavel', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrega', models.CharField(max_length=125, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrega', models.DateField()),
                ('quantidade', models.IntegerField(default=1)),
                ('data_registro', models.DateField(default=datetime.datetime.now)),
                ('beneficiado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='registros.beneficiado')),
                ('orgao_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='registros.orgao')),
                ('responsavel_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registros.tipoentrega')),
                ('tipo_beneficio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registros.beneficio')),
            ],
        ),
    ]
